# Generated by Django 5.2 on 2025-08-05 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_financialgoal_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
